# Generated by Django 5.2.7 on 2025-10-26 21:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Место, где выполнять привычку", max_length=255
                    ),
                ),
                (
                    "time",
                    models.TimeField(help_text="Время выполнения (например, 08:00)"),
                ),
                (
                    "action",
                    models.CharField(help_text="Описание действия", max_length=255),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Является ли привычка приятной (вознаграждением)",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        default=1, help_text="Периодичность в днях (1 = ежедневно)"
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Вознаграждение (если нет связанной привычки)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "execution_time",
                    models.PositiveIntegerField(
                        help_text="Время на выполнение в минутах (max 2 для полезных)",
                        validators=[django.core.validators.MaxValueValidator(2)],
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Публиковать в общий доступ"
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Связанная приятная привычка (только для полезных)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_habits",
                        to="habit.habit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
