# Generated by Django 5.2.7 on 2025-10-28 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="execution_time",
        ),
        migrations.AddField(
            model_name="habit",
            name="duration",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Не более 120 секунд",
                verbose_name="Продолжительность (секунды)",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="name",
            field=models.CharField(
                default="Без названия", max_length=255, verbose_name="Название привычки"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                default=False,
                help_text="Является ли привычка приятной (вознаграждением)",
                verbose_name="Признак приятной привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Не реже 1 раза в 7 дней",
                verbose_name="Периодичность (дни)",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Связанная приятная привычка (только для полезных)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_habits",
                to="habit.habit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Вознаграждение (если нет связанной привычки)",
                max_length=255,
                null=True,
                verbose_name="Вознаграждение",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                help_text="Время выполнения (например, 08:00)",
                verbose_name="Время выполнения",
            ),
        ),
    ]
